parameters:
#    tab_app_part.example.class: TabApp\PartBundle\Example

services:
#    tab_app_part.example:
#        class: %tab_app_part.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
